### ISSUE TITLE
Could you provide the full source code for your example?

### ISSUE THREAD

**Issue by crobicha** [mikecole20/ReSwiftThunk#1]
I am trying to implement the sample code in the readme but I feel like I must be missing something. Can you include the full example code in the repo?

**Comment by mikecole20** [comment]
@crobicha my only implementation is currently in a private project. I'll add a demo project to the repo with a simple action or two over the next couple days (and update the README if any of it is wrong/misleading).

**Comment by crobicha** [comment]
Thanks! At the moment I am trying to understand this line:

```
let result = self.bellhopsSessionManager.request(Router.resetPassword(email: email)).validate().responseJSON()
```

Is bellhopsSessionManager a custom function that sends the request to the ReSwift-Router?

**Comment by crobicha** [comment]
I guess a better question would be - Is it possible to use a thunk without involving the router?

**Comment by mikecole20** [comment]
I just spun up a demo project. https://github.com/mikecole20/ReSwiftThunk/tree/master/Demo/ReSwiftThunkDemo

**Comment by mikecole20** [comment]
In that example, `result` is from [Alamofire](https://github.com/Alamofire/Alamofire). But you can substitute any async task there. In the demo project, I just used an async dispatch to the main thread.

In fact, the only real requirement is that you return something (the return value in `DispatchFunction` requires `Any`). You could run a single, synchronous line of code there if you wanted.

**Comment by crobicha** [comment]
Thanks again Mike, I was able to get it working last night! I'll let you know about any issues I find once I've had a chance to use it a bit more

**Comment by mikecole20** [comment]
@crobicha great to hear! I'll go ahead and close this issue then. If you have any trouble though, don't hesitate to reopen or open a new issue.
