### ISSUE TITLE
Want to create pull request for Swift 4 support

### ISSUE THREAD

**Issue by svdo** [mikecole20/ReSwiftThunk#3]
Hi,

I created a Swift 4 branch in my fork of your repo. I'd like to make a pull request, but for that you would need to create a 'swift4.0' branch in your repo first, as I don't want to make the pull request against master yet. After all, Swift 4 is still in beta...

You can find my branch over here: https://github.com/svdo/ReSwiftThunk/tree/swift4.0

Thanks!

**Comment by mikecole20** [comment]
@svdo, thanks for taking this on! I just pushed a `swift4.0` branch, so feel free to PR your changes to it.
