### ISSUE TITLE
First-Party ReSwift-Thunk library

### ISSUE THREAD

**Issue by mjarvis** [mikecole20/ReSwiftThunk#7]
Hi @mikecole20, we're in the process of setting up a first-party Thunk library for ReSwift at https://github.com/ReSwift/ReSwift-Thunk and wanted to reach out to you in regards to merging this project into there, in the interest of having a single lib for users.
We thank you for your existing contributions and would make sure you have access to continue doing so.

**Comment by mikecole20** [comment]
@mjarvis that sounds great! Let me know what you need from me.

**Comment by mjarvis** [comment]
cc @DivineDominion and @danielmartinprieto

These are the steps I can think of at the moment. Please comment if anyone can think of more! We should create appropriate issues in the repositories to track getting these done.

- [x] ~Add one or more of the ReSwift maintainers as owner to the `ReSwiftThunk` Cocoapods trunk entry (see `pod trunk info ReSwift` to find my cocoapods email address)~
- [x] Investigate the code differences and provide a migration guide in the new repo
- [x] Update this repo readme to indicate that its deprecated and link to the new repo
- [x] Release the first-party lib as either `1.1.0` (or `2.0.0` if this is a code breaking update which it likely is) replacing this repo's existing `1.0.0` release
- [ ] Archive this repository ( https://help.github.com/articles/archiving-a-github-repository/ )

@mikecole20 I've also invited you to be a member of the ReSwift organization which gives you contributor access to all of the ReSwift repos, as well as access to our internal gitter.im chat. You may also want to add us as contributors to this repo if you don't feel you'll have the time to complete the needs on this side.

**Comment by DivineDominion** [comment]
Sounds great! Looking forward to having things merged and hearing from you @mikecole20 :)

**Comment by mikecole20** [comment]
Sounds good to me. I'm traveling at the moment, but will be back home later this weekend. I'll followup then.

**Comment by mikecole20** [comment]
Sorry, I let this slip. I just added all three of the ReSwift pod owners as owners of this pod. I'll also update the readme shortly to direct people to the new repo.

**Comment by DivineDominion** [comment]
@mikecole20 What core concepts are important to you when we merge code bases? This all sounds a bit hasty to me, and I don't want this to look like a takeover to you -- so if you're short on time, I'll do my best when merging code bases into the new org repo.

**Comment by mikecole20** [comment]
Well frankly, there isn't that much code to have an opinion about. 😆 

I started this a while back when I was using ReSwift and saw a need for it. I've since changed jobs and have little time to maintain it (although there really isn't much to it). If you guys have more time to keep it up to date for people to use, then I'm happy.

**Comment by mjarvis** [comment]
v1.1.0 has been released, pointing to the new repository. Deprecated forwards were added such that users should be able to update extremely easily.
Cocoapods trunk has been updated as well: https://cocoapods.org/pods/ReSwiftThunk

@mikecole20 You're welcome to archive this repository if you wish.
